cbg-dbserver:
    build: ./../../../ddbb/config
    ports:
        - "3306:3306"
    volumes:
        - ./../../../ddbb/files:/var/lib/mysql
cbg-webserver:
    build: ./..
    ports:
        - "80:80"
    volumes:
        - ./../../../../../ImageThreadAPI:/var/www/html/image-thread-api.cbg/html_root
        - ./../../../../../ImageThread/webapp_model:/var/www/html/image-thread-api.cbg/html_root/webapp_model
        - ./../../../../../ImageThread/assets:/var/www/html/image-thread-api.cbg/html_root/assets
        - ./../../../../../ImageThread/webapp_controllers:/var/www/html/image-thread-api.cbg/html_root/webapp_controllers
        - ./../../../../../ImageThread/webapp_utilities:/var/www/html/image-thread-api.cbg/html_root/webapp_utilities
    links:
        - cbg-dbserver:mariadb